spring:
  datasource:
    url: jdbc:mysql://localhost:3310/grad_setup?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: douqing
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080